default: &default
  adapter: <%= Settings.app.db.postgresql.adapter %>
  pool: <%= Settings.app.db.postgresql.poolr %>
  username: <%= Settings.app.db.postgresql.username %>
  timeout: <%= Settings.app.db.postgresql.timeout %>
  encoding: <%= Settings.app.db.postgresql.encoding %>
  reconnect: <%= Settings.app.db.postgresql.reconnect %>
  host: <%= Settings.app.db.postgresql.host %>
  database: <%= Settings.app.db.postgresql.db_name %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
