default: &default
  adapter: <%= ENV['DB_ADAPTER'] %>x
  pool: <%= ENV['DB_POOL'] %>
  username: <%= ENV['DB_USERNAME'] %>
  timeout: <%= ENV['DB_TIMEOUT'] %>
  encoding: <%= ENV['DB_ENCODING'] %>
  reconnect: <%= ENV['DB_RECONNECT'] %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
